[book]
title = "正小説"
author = "sungntung"
description = "The web novel series, written by some students."
multilingual = true
language = "ja"


[preprocessor.links]

[preprocessor.index]

[output.html]
default-theme = "navy"
additional-css = ["src/css/main.css"]
site-url = "/"
