[book]
title = "Seishousetsu"
author = "sungntung"
description = "The webpage of the web novel series \"Seishousetsu.\""

[preprocessor.links]

[preprocessor.index]

[output.html]
default-theme = "navy"
additional-css = ["src/css/main.css"]
