[book]
title = "Seishousetu"
author = "sungntung"
description = "The webpage of the web novel series \"Seishousetu.\""

[preprocessor.links]

[preprocessor.index]

[output.html]
default-theme = "ayu"
additional-css = ["src/css/main.css"]
