name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install mdbook
        run: |
           wget https://github.com/rust-lang/mdBook/releases/download/v0.4.12/mdbook-v0.4.12-x86_64-unknown-linux-gnu.tar.gz
           tar xvf mdbook-v0.4.12-x86_64-unknown-linux-gnu.tar.gz
           chmod +x ./mdbook
      - name: Build and test site
        run: |
          cd ../
          mdbook build
          mdbook test
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
