name: Publish

on:
  push:
    branches: |
            [main]
            [langsearch]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install mdbook
        run: |
          git clone https://github.com/sjkim04/mdBook.git
          cargo install --path .
      - name: Build and test site
        run: |
          ./mdbook build
          ./mdbook test
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
